INSERT INTO student VALUES (all_users_seq.NEXTVAL,'Q','HABIBUR RAHMAN','REBEKA SULTANA','v','c',NULL,55,9,2017);
INSERT INTO student VALUES (all_users_seq.NEXTVAL,'E','HABIBUR RAHMAN','REBEKA SULTANA','v','c',NULL,55,9,2017);
INSERT INTO student VALUES (all_users_seq.NEXTVAL,'R','HABIBUR RAHMAN','REBEKA SULTANA','v','c',NULL,55,9,2017);
INSERT INTO student VALUES (all_users_seq.NEXTVAL,'T','HABIBUR RAHMAN','REBEKA SULTANA','v','c',NULL,55,9,2017);
INSERT INTO student VALUES (all_users_seq.NEXTVAL,'Y','HABIBUR RAHMAN','REBEKA SULTANA','v','c',NULL,55,9,2017);
INSERT INTO student VALUES (all_users_seq.NEXTVAL,'F','HABIBUR RAHMAN','REBEKA SULTANA','v','c',NULL,55,9,2017);
INSERT INTO student VALUES (all_users_seq.NEXTVAL,'D','HABIBUR RAHMAN','REBEKA SULTANA','v','c',NULL,55,9,2017);
INSERT INTO student VALUES (all_users_seq.NEXTVAL,'A','HABIBUR RAHMAN','REBEKA SULTANA','v','c',NULL,55,9,2017);
INSERT INTO student VALUES (all_users_seq.NEXTVAL,'B','HABIBUR RAHMAN','REBEKA SULTANA','v','c',NULL,55,9,2017);

INSERT INTO teacher VALUES (all_users_seq.NEXTVAL,'Jk','Tanvir','Zaman',NULL,DEFAULT,DEFAULT,10);
INSERT INTO teacher VALUES (all_users_seq.NEXTVAL,'Jf','Tanvir','Zaman',NULL,DEFAULT,DEFAULT,10);
INSERT INTO teacher VALUES (all_users_seq.NEXTVAL,'Jss','Tanvir','Zaman',NULL,DEFAULT,DEFAULT,10);
INSERT INTO teacher VALUES (all_users_seq.NEXTVAL,'Jks','Tanvir','Zaman',NULL,DEFAULT,DEFAULT,10);
INSERT INTO teacher VALUES (all_users_seq.NEXTVAL,'Jfs','Tanvir','Zaman',NULL,DEFAULT,DEFAULT,10);
INSERT INTO teacher VALUES (all_users_seq.NEXTVAL,'Jss','Tanvir','Zaman',NULL,DEFAULT,DEFAULT,10);