INSERT INTO student
    VALUES (
    NULL,
    'TANVIR',
    'HABIBUR RAHMAN',
    'REBEKA SULTANA',
    NULL,
    55,
    9,
    2017
    );
INSERT INTO student
    VALUES (
    NULL,
    'TONOY',
    'NAZMUL HOSSAIN'
    ,NULL,
    NULL,
    56,
    9,
    2017
    );
INSERT INTO student 
    VALUES (
    NULL,
    'ALICIA',
    'PETER PERKER',
    'GWEN STACY',
    '112B,BEAKER STREET',
    86,
    6,
    2015
    );
INSERT INTO student 
    VALUES (
    NULL,
    'GWENA',
    'PETER WALKER',
    'ALICE BOQUET',
    '112B,BEAKRE STREET',
    05,
    6,
    2015
    );
INSERT INTO student 
    VALUES (
    NULL,
    'ALICIANA2',
    'ANTHONY',
    'MANDY',
    'NEW YORK',
    15,
    6,
    2015
    );
INSERT INTO student 
    VALUES (
    NULL,
    'GWEN',
    'PETER WALKER',
    'ALICE BOQUET',
    'WORKERS STREET',
    05,
    30,
    2015
    );
INSERT INTO student 
    VALUES (
    NULL,
    'ANTHONY',
    'TONY STARK',
    NULL,
    'WAPDA ROAD,
    ASHUGONJ',
    09,
    5,
    2019
    );
INSERT INTO student 
    VALUES (
    NULL,
    'MD.KAMRUZZAMAN',
    'HABIBUR RAHAMAN',
    'REBEKA SULTANA',
    'WAPDA ROAD, ASHUGANJ, BRAHMANBARIA, BANGALDESH',
    40,
    9,
    2016
    );
INSERT INTO student 
    VALUES (
    NULL,
    'GLAMORA',
    'THOMAS ALVA',
    'GWEN TENISON',
    'NEW YORK',
    15,
    7,
    2022
    );
INSERT INTO student 
    VALUES (
    NULL,
    'TONY STARK',
    'ANTHONEY STARK',
    'GWENDOLIN STACY',
    'WORKERS STREET',
    3,
    5,
    2010
    );