INSERT INTO teacher 
    VALUES (
    NULL,
    'TANVIR_t',
    NULL,
    NULL,
    NULL,
    'senior',
    DEFAULT,
    2059
    );
INSERT INTO teacher 
    VALUES (
    NULL,
    'ALICIA_t',
    NULL,
    NULL,
    NULL,
    'senior',
    DEFAULT,
    5611
    );
INSERT INTO teacher 
    VALUES (
    NULL,
    'GWEN_t',
    NULL,
    NULL,
    NULL,
    'senior',
    DEFAULT,
    5691
    );
INSERT INTO teacher 
    VALUES (
    NULL,
    'JOYCE_t',
    NULL,
    NULL,
    NULL,
    'senior',
    DEFAULT,
    5682
    );
INSERT INTO teacher 
    VALUES (
    NULL,
    'THEODOR_t',
    NULL,
    NULL,
    NULL,
    'senior',
    DEFAULT,
    5540
    );
INSERT INTO teacher 
    VALUES (
    NULL,
    'ZAMAN_t',
    NULL,
    NULL,
    NULL,
    'assistant',
    DEFAULT,
    2059
    );
INSERT INTO teacher 
    VALUES (
    NULL,
    'ALICE_t',
    NULL,
    NULL,
    NULL,
    'senior',
    DEFAULT,
    5611
    );
INSERT INTO teacher 
    VALUES (
    NULL,
    'GWENOLIN_t',
    NULL,
    NULL,
    NULL,
    'junior',
    DEFAULT,
    5691
    );
INSERT INTO teacher 
    VALUES (
    NULL,
    'JOYCEER_t',
    NULL,
    NULL,
    NULL,
    'senior',
    DEFAULT,
    5682
    );
INSERT INTO teacher 
    VALUES (
    NULL,
    'THEODOR_t',
    NULL,
    NULL,
    NULL,
    'senior',
    DEFAULT,
    5540
    );

DESCRIBE teacher;
SELECT * FROM teacher;